### ISSUE TITLE
What is exact format for checkpoint or lora name in Save Image parameters?

### ISSUE THREAD

**Issue by EnragedAntelope** [Rvage0815/ComfyUI-RvTools_v2#2]
Hi,
Thanks for making these nodes. I am using the Save Image node and I have all inputs populated in the Pipe In Generation Data node except for Pipe (as I am not using the checkpoint loader etc from RV Tools). 

You can see the format of the checkpoint/lora name I'm using in this image. However when I upload to Civit I do not see it resolving that checkpoint name. Is there a certain format or trick to get Civit to identify that info using your node?

![image](https://github.com/user-attachments/assets/3bb5fe5a-430e-4b41-84a1-02a85c3b10b5)

Thank you!

**Comment by Rvage0815** [comment]
the format is the filename with extension, the save image node tries to find it in the checkpoint/diffusion_model or lora folder and creates a hash value if found, if its unable to find the file you should see  a msg in the command prompt. civitai is using this hash to assign your image to the model, but for this it must exist on the site and a hash value must have been stored. which is not the case for flux1.dev for example.

**Comment by Rvage0815** [comment]
i noticed that is doesn't work for all of the gguf models but i can't tell you why sry. for the most models and loras that i've used so far it works 🤷‍♂️

![Screenshot 2024-12-05 022225](https://github.com/user-attachments/assets/f957c65f-4dd8-4149-a2e4-d41b1c1cf7dc)

https://civitai.com/images/43733391

**Comment by Rvage0815** [comment]
the format is the filename with extension, the save image node tries to find it in the checkpoint/diffusion_model or lora folder and creates a hash value if found, if its unable to find the file you should see a msg in the command prompt. civitai is using this hash to assign your image to the model, but for this it must exist on the site and a hash value must have been stored. which is not the case for flux1.dev for example.

*edit: i've noticed that there is an issue with the hash value, i've to check that later.

the reason why the gguf models are not recognized is because they were uploaded as a zip file and the stored hash value is from the zip file not from the model.

**Comment by Rvage0815** [comment]
the format is the filename with extension, the save image node tries to find it in the checkpoint/diffusion_model or lora folder and creates a hash value if found, if its unable to find the file you should see a msg in the command prompt. civitai is using this hash to assign your image to the model, but for this it must exist on the site and a hash value must have been stored. which is not the case for flux1.dev for example.

*edit: i've noticed that there is an issue with the hash value, i've to check that later.

the reason why the gguf models are not recognized is because they were uploaded as a zip file and the stored hash value is from the zip file not from the model.

for the most other models and loras that i've used so far it works.
![Screenshot 2024-12-05 022225](https://github.com/user-attachments/assets/5dd3f135-0be4-443e-945c-3620c91cb920)



https://civitai.com/images/43733391
